services:
  frontend:
    image: web-topic-final-frontend
    build:
      context: ./web-topic-final-frontend
    command: npm start
    volumes:
      - ./web-topic-final-frontend/src:/frontend/src
      - ./web-topic-final-frontend/public:/frontend/public
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://127.0.0.1:5000
      REACT_APP_CATEGORIES_PAIR: roleplay:RP,moba:MB,sandbox:SB,arcade:AE,retro:RT,tower defense:TD,explore:EX,adventure:AD,survival:SV,battle royale:BR,hack and slash:HS,parkour:PK,horror:HR,platformmer:PL,strategy:ST,simulation:SM,thriller:TH,racing:RC,rouge like:RL,cooking:CK,music:MS
    ports:
      - 3000:3000

  frontend-css:
    image: web-topic-final-frontend-css
    command: npm run build-css-watch
    volumes:
      - ./web-topic-final-frontend/src:/frontend/src
    build:
      context: ./web-topic-final-frontend
    tty: true

  backend:
    image: web-topic-final-backend
    build:
      context: ./web-topic-final-backend
    ports:
      - 5000:5000
    volumes:
      - ./web-topic-final-backend/src:/backend/src
      - ./web-topic-final-backend/public:/backend/public
    environment:
      PORT: 5000
      ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      MODE: dev
      SIGNING_KEY: bYzYtOw6WzUvijlYJkQ23BjeS5RsB2daKYFKtgU7MJU=
      ACCESS_TOKEN_DURATION_IN_HOUR: 1
      REFRESH_TOKEN_DURATION_IN_HOUR: 24
      CATEGORIES_PAIR: roleplay:RP,moba:MB,sandbox:SB,arcade:AE,retro:RT,tower defense:TD,explore:EX,adventure:AD,survival:SV,battle royale:BR,hack and slash:HS,parkour:PK,horror:HR,platformmer:PL,strategy:ST,simulation:SM,thriller:TH,racing:RC,rouge like:RL,cooking:CK,music:MS
      WORK_FACTOR: 13
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_DATABASE: game-store
      MONGODB_GAMES_COLLECTION: games
      MONGODB_USERS_COLLECTION: users
      MONGODB_APPNAME:
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
